[package]
name = "raw"
version = "0.1.0"
edition = "2021"

[profile.release]
panic = "abort"

[dependencies]
libc = { version = "0.2.135", default-features = false }

[lib]
crate-type = ["cdylib"]

[build-dependencies]
bindgen = "0.61.0"
